version: '3'
services:
  node:
    container_name: node_server
    restart: always
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: yarn dev
    networks:
      - common
    environment:
     
       MONGO_URL: 'mongodb://mongo/DATN_Moive'
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common
networks:
 common: